version: "3.9"
services:
  postgres:
    container_name: postgres-intern-release
    image: postgres:latest
    environment:
        POSTGRES_DB: "InternCatalog"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "123"
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data

  api:
    build:
        context: .
        dockerfile: src/InternPortal.API/Dockerfile
    ports:
        - "5000:80"
    depends_on:
        - postgres

  client:
    build:
      context: .
      dockerfile: src/InternPortal.Client/Dockerfile
    ports:
      - "7100:80"
    depends_on:
      - api

volumes:
    postgres-data: